//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardValidationService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public decimal Number { get; set; }
        public System.DateTime ExpiryDate { get; set; }
    }
}
